### ISSUE TITLE
Feature: New user directions

### ISSUE THREAD

**Issue by luckyNoodles** [HTYY-Enterprises/4U2Write#28]
I had no idea what to do when the page opened. The pop up blocked me from doing anything asked me to choose a prompt but I didn't know what it meant or why. I had to restart a few times before I understood what was going on. Maybe something in the first pop up that says "A writing prompt can get you started writing quickly if you don't have a topic yet and just want to get started. Do you want a writing topic to get you started?"

**Comment by ayearwood81** [comment]
Good tip.  Changed the opening pop up modal to give a bit more detailed instructions.  Thanks!
